#!/bin/bash

WRAPPER="$1"; shift
case "$WRAPPER" in
    urban-terror)
        exec "$SNAP"/Quake3-UrT.x86_64 "$@"
        ;;
    urban-terror.dedicated)
        exec "$SNAP"/Quake3-UrT-Ded.x86_64 "$@"
        ;;
esac