#!/bin/bash

WRAPPER="$1"; shift
case "$WRAPPER" in
    urban-terror)

        # Required for audio to work on Wayland, hooks into local pulse server.
        if test -S "${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native; then
            export PULSE_SERVER=unix:"${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native
        fi

        # Normal or protocol urt://<IP>:<PORT> launch
        if test "${1:0:3}" == "urt"; then
            exec "$SNAP"/Quake3-UrT.x86_64 connect "${1:6}"
        else
            exec "$SNAP"/Quake3-UrT.x86_64 "$@"
        fi
        ;;
    urban-terror.dedicated)
        exec "$SNAP"/Quake3-UrT-Ded.x86_64 "$@"
        ;;
esac