name: urban-terror
summary: Free multiplayer first person shooter developed by FrozenSand
description: |
  Urban Terror can be described as a Hollywood tactical shooter;
  somewhat realism based, but the motto is "fun over realism".
  This results in a very unique, enjoyable and addictive game.

version: '4.3.4'
base: core18
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  urban-terror:
    command: UrbanTerror43/Quake3-UrT.x86_64
    environment:
      DISABLE_WAYLAND: 1
      SDL_AUDIODRIVER: pulse
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback

  dedicated:
    command: UrbanTerror43/Quake3-UrT-Ded.x86_64
    plugs:
      - network
      - network-bind

parts:
  urban-terror:
    source: http://cdn.urbanterror.info/urt/43/releases/zips/UrbanTerror434_full.zip
    plugin: dump
    stage-packages:
      - libasound2
      - libbsd0
      - libcurl3
      - libgcc1
      - libglu1-mesa
      - libjpeg62
      - libpulse0
      - libsdl1.2debian
      - libstdc++6
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxpm4
      - libxxf86vm1
      - zlib1g
      - libslang2
      - freeglut3
    prime:
      - -UrbanTerror43/Quake3-UrT.app
      - -UrbanTerror43/Quake3-UrT.exe
      - -UrbanTerror43/Quake3-UrT.i386
      - -UrbanTerror43/Quake3-UrT-Ded.exe
      - -UrbanTerror43/Quake3-UrT-Ded.i386
